theme = "PaperMod"
baseURL = "https://justinmathew.com/"
canonifyURLs = true
languageCode = 'en-us'
title = 'Department of random technical stuffs'
[params.homeInfoParams]
  Title = "Hey, I'm Justin ðŸ‘‹"
  Content = "Welcome to my blog â€” Its some random thoughts from a foolish developer!"
[params.math]
  enable = true  
[outputs]
  home = ["HTML", "RSS", "JSON"]
[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 10
[[menu.main]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 20
[params.comments]
  enable=true
[services.googleAnalytics]
  ID = "G-WNH0R0YX3N"
[markup.goldmark.renderer]
  unsafe = true